/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthRouteImport } from './routes/health'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProvidersIndexRouteImport } from './routes/providers/index'
import { Route as ModelsIndexRouteImport } from './routes/models/index'
import { Route as V1ResponsesRouteImport } from './routes/v1/responses'
import { Route as V1ModelsRouteImport } from './routes/v1/models'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiUsageRouteImport } from './routes/api/usage'
import { Route as ApiModelsRouteImport } from './routes/api/models'
import { Route as ApiAccountsRouteImport } from './routes/api/accounts'
import { Route as V1ChatCompletionsRouteImport } from './routes/v1/chat/completions'
import { Route as BackendApiCodexResponsesRouteImport } from './routes/backend-api/codex/responses'
import { Route as BackendApiCodexModelsRouteImport } from './routes/backend-api/codex/models'
import { Route as ApiSystemVersionRouteImport } from './routes/api/system/version'
import { Route as ApiSystemOpenRouteImport } from './routes/api/system/open'
import { Route as ApiProvidersOpenrouterRouteImport } from './routes/api/providers/openrouter'
import { Route as ApiProvidersOpencodeZenRouteImport } from './routes/api/providers/opencode-zen'
import { Route as ApiProvidersOllamaCloudRouteImport } from './routes/api/providers/ollama-cloud'
import { Route as ApiProvidersChatgptRouteImport } from './routes/api/providers/chatgpt'
import { Route as ApiOauthStatusRouteImport } from './routes/api/oauth/status'
import { Route as ApiOauthStartRouteImport } from './routes/api/oauth/start'
import { Route as ApiOauthManualCallbackRouteImport } from './routes/api/oauth/manual-callback'
import { Route as ApiOauthCompleteRouteImport } from './routes/api/oauth/complete'
import { Route as ApiCodexUsageLimitRouteImport } from './routes/api/codex/usage-limit'
import { Route as ApiCodexModelCatalogRouteImport } from './routes/api/codex/model-catalog'
import { Route as ApiCodexInstallConfigRouteImport } from './routes/api/codex/install-config'
import { Route as BackendApiWhamAgentIdentitiesJwksRouteImport } from './routes/backend-api/wham/agent-identities/jwks'
import { Route as BackendApiCodexSafetyArcRouteImport } from './routes/backend-api/codex/safety/arc'
import { Route as BackendApiCodexResponsesCompactRouteImport } from './routes/backend-api/codex/responses/compact'
import { Route as BackendApiCodexRealtimeCallsRouteImport } from './routes/backend-api/codex/realtime/calls'
import { Route as BackendApiCodexMemoriesTrace_summarizeRouteImport } from './routes/backend-api/codex/memories/trace_summarize'
import { Route as BackendApiCodexAnalyticsEventsEventsRouteImport } from './routes/backend-api/codex/analytics-events/events'
import { Route as BackendApiCodexAgentIdentitiesJwksRouteImport } from './routes/backend-api/codex/agent-identities/jwks'
import { Route as ApiSystemUpdateCheckRouteImport } from './routes/api/system/update/check'
import { Route as ApiSystemUpdateApplyRouteImport } from './routes/api/system/update/apply'
import { Route as BackendApiCodexThreadGoalSetRouteImport } from './routes/backend-api/codex/thread/goal/set'
import { Route as BackendApiCodexThreadGoalGetRouteImport } from './routes/backend-api/codex/thread/goal/get'
import { Route as BackendApiCodexThreadGoalClearRouteImport } from './routes/backend-api/codex/thread/goal/clear'

const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIndexRoute = ProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ResponsesRoute = V1ResponsesRouteImport.update({
  id: '/v1/responses',
  path: '/v1/responses',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ModelsRoute = V1ModelsRouteImport.update({
  id: '/v1/models',
  path: '/v1/models',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsageRoute = ApiUsageRouteImport.update({
  id: '/api/usage',
  path: '/api/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountsRoute = ApiAccountsRouteImport.update({
  id: '/api/accounts',
  path: '/api/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ChatCompletionsRoute = V1ChatCompletionsRouteImport.update({
  id: '/v1/chat/completions',
  path: '/v1/chat/completions',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendApiCodexResponsesRoute =
  BackendApiCodexResponsesRouteImport.update({
    id: '/backend-api/codex/responses',
    path: '/backend-api/codex/responses',
    getParentRoute: () => rootRouteImport,
  } as any)
const BackendApiCodexModelsRoute = BackendApiCodexModelsRouteImport.update({
  id: '/backend-api/codex/models',
  path: '/backend-api/codex/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemVersionRoute = ApiSystemVersionRouteImport.update({
  id: '/api/system/version',
  path: '/api/system/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemOpenRoute = ApiSystemOpenRouteImport.update({
  id: '/api/system/open',
  path: '/api/system/open',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvidersOpenrouterRoute = ApiProvidersOpenrouterRouteImport.update({
  id: '/api/providers/openrouter',
  path: '/api/providers/openrouter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvidersOpencodeZenRoute = ApiProvidersOpencodeZenRouteImport.update({
  id: '/api/providers/opencode-zen',
  path: '/api/providers/opencode-zen',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvidersOllamaCloudRoute = ApiProvidersOllamaCloudRouteImport.update({
  id: '/api/providers/ollama-cloud',
  path: '/api/providers/ollama-cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvidersChatgptRoute = ApiProvidersChatgptRouteImport.update({
  id: '/api/providers/chatgpt',
  path: '/api/providers/chatgpt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthStatusRoute = ApiOauthStatusRouteImport.update({
  id: '/api/oauth/status',
  path: '/api/oauth/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthStartRoute = ApiOauthStartRouteImport.update({
  id: '/api/oauth/start',
  path: '/api/oauth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthManualCallbackRoute = ApiOauthManualCallbackRouteImport.update({
  id: '/api/oauth/manual-callback',
  path: '/api/oauth/manual-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthCompleteRoute = ApiOauthCompleteRouteImport.update({
  id: '/api/oauth/complete',
  path: '/api/oauth/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodexUsageLimitRoute = ApiCodexUsageLimitRouteImport.update({
  id: '/api/codex/usage-limit',
  path: '/api/codex/usage-limit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodexModelCatalogRoute = ApiCodexModelCatalogRouteImport.update({
  id: '/api/codex/model-catalog',
  path: '/api/codex/model-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodexInstallConfigRoute = ApiCodexInstallConfigRouteImport.update({
  id: '/api/codex/install-config',
  path: '/api/codex/install-config',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendApiWhamAgentIdentitiesJwksRoute =
  BackendApiWhamAgentIdentitiesJwksRouteImport.update({
    id: '/backend-api/wham/agent-identities/jwks',
    path: '/backend-api/wham/agent-identities/jwks',
    getParentRoute: () => rootRouteImport,
  } as any)
const BackendApiCodexSafetyArcRoute =
  BackendApiCodexSafetyArcRouteImport.update({
    id: '/backend-api/codex/safety/arc',
    path: '/backend-api/codex/safety/arc',
    getParentRoute: () => rootRouteImport,
  } as any)
const BackendApiCodexResponsesCompactRoute =
  BackendApiCodexResponsesCompactRouteImport.update({
    id: '/compact',
    path: '/compact',
    getParentRoute: () => BackendApiCodexResponsesRoute,
  } as any)
const BackendApiCodexRealtimeCallsRoute =
  BackendApiCodexRealtimeCallsRouteImport.update({
    id: '/backend-api/codex/realtime/calls',
    path: '/backend-api/codex/realtime/calls',
    getParentRoute: () => rootRouteImport,
  } as any)
const BackendApiCodexMemoriesTrace_summarizeRoute =
  BackendApiCodexMemoriesTrace_summarizeRouteImport.update({
    id: '/backend-api/codex/memories/trace_summarize',
    path: '/backend-api/codex/memories/trace_summarize',
    getParentRoute: () => rootRouteImport,
  } as any)
const BackendApiCodexAnalyticsEventsEventsRoute =
  BackendApiCodexAnalyticsEventsEventsRouteImport.update({
    id: '/backend-api/codex/analytics-events/events',
    path: '/backend-api/codex/analytics-events/events',
    getParentRoute: () => rootRouteImport,
  } as any)
const BackendApiCodexAgentIdentitiesJwksRoute =
  BackendApiCodexAgentIdentitiesJwksRouteImport.update({
    id: '/backend-api/codex/agent-identities/jwks',
    path: '/backend-api/codex/agent-identities/jwks',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSystemUpdateCheckRoute = ApiSystemUpdateCheckRouteImport.update({
  id: '/api/system/update/check',
  path: '/api/system/update/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemUpdateApplyRoute = ApiSystemUpdateApplyRouteImport.update({
  id: '/api/system/update/apply',
  path: '/api/system/update/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendApiCodexThreadGoalSetRoute =
  BackendApiCodexThreadGoalSetRouteImport.update({
    id: '/backend-api/codex/thread/goal/set',
    path: '/backend-api/codex/thread/goal/set',
    getParentRoute: () => rootRouteImport,
  } as any)
const BackendApiCodexThreadGoalGetRoute =
  BackendApiCodexThreadGoalGetRouteImport.update({
    id: '/backend-api/codex/thread/goal/get',
    path: '/backend-api/codex/thread/goal/get',
    getParentRoute: () => rootRouteImport,
  } as any)
const BackendApiCodexThreadGoalClearRoute =
  BackendApiCodexThreadGoalClearRouteImport.update({
    id: '/backend-api/codex/thread/goal/clear',
    path: '/backend-api/codex/thread/goal/clear',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/api/accounts': typeof ApiAccountsRoute
  '/api/models': typeof ApiModelsRoute
  '/api/usage': typeof ApiUsageRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/v1/models': typeof V1ModelsRoute
  '/v1/responses': typeof V1ResponsesRoute
  '/models/': typeof ModelsIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/api/codex/install-config': typeof ApiCodexInstallConfigRoute
  '/api/codex/model-catalog': typeof ApiCodexModelCatalogRoute
  '/api/codex/usage-limit': typeof ApiCodexUsageLimitRoute
  '/api/oauth/complete': typeof ApiOauthCompleteRoute
  '/api/oauth/manual-callback': typeof ApiOauthManualCallbackRoute
  '/api/oauth/start': typeof ApiOauthStartRoute
  '/api/oauth/status': typeof ApiOauthStatusRoute
  '/api/providers/chatgpt': typeof ApiProvidersChatgptRoute
  '/api/providers/ollama-cloud': typeof ApiProvidersOllamaCloudRoute
  '/api/providers/opencode-zen': typeof ApiProvidersOpencodeZenRoute
  '/api/providers/openrouter': typeof ApiProvidersOpenrouterRoute
  '/api/system/open': typeof ApiSystemOpenRoute
  '/api/system/version': typeof ApiSystemVersionRoute
  '/backend-api/codex/models': typeof BackendApiCodexModelsRoute
  '/backend-api/codex/responses': typeof BackendApiCodexResponsesRouteWithChildren
  '/v1/chat/completions': typeof V1ChatCompletionsRoute
  '/api/system/update/apply': typeof ApiSystemUpdateApplyRoute
  '/api/system/update/check': typeof ApiSystemUpdateCheckRoute
  '/backend-api/codex/agent-identities/jwks': typeof BackendApiCodexAgentIdentitiesJwksRoute
  '/backend-api/codex/analytics-events/events': typeof BackendApiCodexAnalyticsEventsEventsRoute
  '/backend-api/codex/memories/trace_summarize': typeof BackendApiCodexMemoriesTrace_summarizeRoute
  '/backend-api/codex/realtime/calls': typeof BackendApiCodexRealtimeCallsRoute
  '/backend-api/codex/responses/compact': typeof BackendApiCodexResponsesCompactRoute
  '/backend-api/codex/safety/arc': typeof BackendApiCodexSafetyArcRoute
  '/backend-api/wham/agent-identities/jwks': typeof BackendApiWhamAgentIdentitiesJwksRoute
  '/backend-api/codex/thread/goal/clear': typeof BackendApiCodexThreadGoalClearRoute
  '/backend-api/codex/thread/goal/get': typeof BackendApiCodexThreadGoalGetRoute
  '/backend-api/codex/thread/goal/set': typeof BackendApiCodexThreadGoalSetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/api/accounts': typeof ApiAccountsRoute
  '/api/models': typeof ApiModelsRoute
  '/api/usage': typeof ApiUsageRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/v1/models': typeof V1ModelsRoute
  '/v1/responses': typeof V1ResponsesRoute
  '/models': typeof ModelsIndexRoute
  '/providers': typeof ProvidersIndexRoute
  '/api/codex/install-config': typeof ApiCodexInstallConfigRoute
  '/api/codex/model-catalog': typeof ApiCodexModelCatalogRoute
  '/api/codex/usage-limit': typeof ApiCodexUsageLimitRoute
  '/api/oauth/complete': typeof ApiOauthCompleteRoute
  '/api/oauth/manual-callback': typeof ApiOauthManualCallbackRoute
  '/api/oauth/start': typeof ApiOauthStartRoute
  '/api/oauth/status': typeof ApiOauthStatusRoute
  '/api/providers/chatgpt': typeof ApiProvidersChatgptRoute
  '/api/providers/ollama-cloud': typeof ApiProvidersOllamaCloudRoute
  '/api/providers/opencode-zen': typeof ApiProvidersOpencodeZenRoute
  '/api/providers/openrouter': typeof ApiProvidersOpenrouterRoute
  '/api/system/open': typeof ApiSystemOpenRoute
  '/api/system/version': typeof ApiSystemVersionRoute
  '/backend-api/codex/models': typeof BackendApiCodexModelsRoute
  '/backend-api/codex/responses': typeof BackendApiCodexResponsesRouteWithChildren
  '/v1/chat/completions': typeof V1ChatCompletionsRoute
  '/api/system/update/apply': typeof ApiSystemUpdateApplyRoute
  '/api/system/update/check': typeof ApiSystemUpdateCheckRoute
  '/backend-api/codex/agent-identities/jwks': typeof BackendApiCodexAgentIdentitiesJwksRoute
  '/backend-api/codex/analytics-events/events': typeof BackendApiCodexAnalyticsEventsEventsRoute
  '/backend-api/codex/memories/trace_summarize': typeof BackendApiCodexMemoriesTrace_summarizeRoute
  '/backend-api/codex/realtime/calls': typeof BackendApiCodexRealtimeCallsRoute
  '/backend-api/codex/responses/compact': typeof BackendApiCodexResponsesCompactRoute
  '/backend-api/codex/safety/arc': typeof BackendApiCodexSafetyArcRoute
  '/backend-api/wham/agent-identities/jwks': typeof BackendApiWhamAgentIdentitiesJwksRoute
  '/backend-api/codex/thread/goal/clear': typeof BackendApiCodexThreadGoalClearRoute
  '/backend-api/codex/thread/goal/get': typeof BackendApiCodexThreadGoalGetRoute
  '/backend-api/codex/thread/goal/set': typeof BackendApiCodexThreadGoalSetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/api/accounts': typeof ApiAccountsRoute
  '/api/models': typeof ApiModelsRoute
  '/api/usage': typeof ApiUsageRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/v1/models': typeof V1ModelsRoute
  '/v1/responses': typeof V1ResponsesRoute
  '/models/': typeof ModelsIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/api/codex/install-config': typeof ApiCodexInstallConfigRoute
  '/api/codex/model-catalog': typeof ApiCodexModelCatalogRoute
  '/api/codex/usage-limit': typeof ApiCodexUsageLimitRoute
  '/api/oauth/complete': typeof ApiOauthCompleteRoute
  '/api/oauth/manual-callback': typeof ApiOauthManualCallbackRoute
  '/api/oauth/start': typeof ApiOauthStartRoute
  '/api/oauth/status': typeof ApiOauthStatusRoute
  '/api/providers/chatgpt': typeof ApiProvidersChatgptRoute
  '/api/providers/ollama-cloud': typeof ApiProvidersOllamaCloudRoute
  '/api/providers/opencode-zen': typeof ApiProvidersOpencodeZenRoute
  '/api/providers/openrouter': typeof ApiProvidersOpenrouterRoute
  '/api/system/open': typeof ApiSystemOpenRoute
  '/api/system/version': typeof ApiSystemVersionRoute
  '/backend-api/codex/models': typeof BackendApiCodexModelsRoute
  '/backend-api/codex/responses': typeof BackendApiCodexResponsesRouteWithChildren
  '/v1/chat/completions': typeof V1ChatCompletionsRoute
  '/api/system/update/apply': typeof ApiSystemUpdateApplyRoute
  '/api/system/update/check': typeof ApiSystemUpdateCheckRoute
  '/backend-api/codex/agent-identities/jwks': typeof BackendApiCodexAgentIdentitiesJwksRoute
  '/backend-api/codex/analytics-events/events': typeof BackendApiCodexAnalyticsEventsEventsRoute
  '/backend-api/codex/memories/trace_summarize': typeof BackendApiCodexMemoriesTrace_summarizeRoute
  '/backend-api/codex/realtime/calls': typeof BackendApiCodexRealtimeCallsRoute
  '/backend-api/codex/responses/compact': typeof BackendApiCodexResponsesCompactRoute
  '/backend-api/codex/safety/arc': typeof BackendApiCodexSafetyArcRoute
  '/backend-api/wham/agent-identities/jwks': typeof BackendApiWhamAgentIdentitiesJwksRoute
  '/backend-api/codex/thread/goal/clear': typeof BackendApiCodexThreadGoalClearRoute
  '/backend-api/codex/thread/goal/get': typeof BackendApiCodexThreadGoalGetRoute
  '/backend-api/codex/thread/goal/set': typeof BackendApiCodexThreadGoalSetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/api/accounts'
    | '/api/models'
    | '/api/usage'
    | '/auth/callback'
    | '/v1/models'
    | '/v1/responses'
    | '/models/'
    | '/providers/'
    | '/api/codex/install-config'
    | '/api/codex/model-catalog'
    | '/api/codex/usage-limit'
    | '/api/oauth/complete'
    | '/api/oauth/manual-callback'
    | '/api/oauth/start'
    | '/api/oauth/status'
    | '/api/providers/chatgpt'
    | '/api/providers/ollama-cloud'
    | '/api/providers/opencode-zen'
    | '/api/providers/openrouter'
    | '/api/system/open'
    | '/api/system/version'
    | '/backend-api/codex/models'
    | '/backend-api/codex/responses'
    | '/v1/chat/completions'
    | '/api/system/update/apply'
    | '/api/system/update/check'
    | '/backend-api/codex/agent-identities/jwks'
    | '/backend-api/codex/analytics-events/events'
    | '/backend-api/codex/memories/trace_summarize'
    | '/backend-api/codex/realtime/calls'
    | '/backend-api/codex/responses/compact'
    | '/backend-api/codex/safety/arc'
    | '/backend-api/wham/agent-identities/jwks'
    | '/backend-api/codex/thread/goal/clear'
    | '/backend-api/codex/thread/goal/get'
    | '/backend-api/codex/thread/goal/set'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/api/accounts'
    | '/api/models'
    | '/api/usage'
    | '/auth/callback'
    | '/v1/models'
    | '/v1/responses'
    | '/models'
    | '/providers'
    | '/api/codex/install-config'
    | '/api/codex/model-catalog'
    | '/api/codex/usage-limit'
    | '/api/oauth/complete'
    | '/api/oauth/manual-callback'
    | '/api/oauth/start'
    | '/api/oauth/status'
    | '/api/providers/chatgpt'
    | '/api/providers/ollama-cloud'
    | '/api/providers/opencode-zen'
    | '/api/providers/openrouter'
    | '/api/system/open'
    | '/api/system/version'
    | '/backend-api/codex/models'
    | '/backend-api/codex/responses'
    | '/v1/chat/completions'
    | '/api/system/update/apply'
    | '/api/system/update/check'
    | '/backend-api/codex/agent-identities/jwks'
    | '/backend-api/codex/analytics-events/events'
    | '/backend-api/codex/memories/trace_summarize'
    | '/backend-api/codex/realtime/calls'
    | '/backend-api/codex/responses/compact'
    | '/backend-api/codex/safety/arc'
    | '/backend-api/wham/agent-identities/jwks'
    | '/backend-api/codex/thread/goal/clear'
    | '/backend-api/codex/thread/goal/get'
    | '/backend-api/codex/thread/goal/set'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/api/accounts'
    | '/api/models'
    | '/api/usage'
    | '/auth/callback'
    | '/v1/models'
    | '/v1/responses'
    | '/models/'
    | '/providers/'
    | '/api/codex/install-config'
    | '/api/codex/model-catalog'
    | '/api/codex/usage-limit'
    | '/api/oauth/complete'
    | '/api/oauth/manual-callback'
    | '/api/oauth/start'
    | '/api/oauth/status'
    | '/api/providers/chatgpt'
    | '/api/providers/ollama-cloud'
    | '/api/providers/opencode-zen'
    | '/api/providers/openrouter'
    | '/api/system/open'
    | '/api/system/version'
    | '/backend-api/codex/models'
    | '/backend-api/codex/responses'
    | '/v1/chat/completions'
    | '/api/system/update/apply'
    | '/api/system/update/check'
    | '/backend-api/codex/agent-identities/jwks'
    | '/backend-api/codex/analytics-events/events'
    | '/backend-api/codex/memories/trace_summarize'
    | '/backend-api/codex/realtime/calls'
    | '/backend-api/codex/responses/compact'
    | '/backend-api/codex/safety/arc'
    | '/backend-api/wham/agent-identities/jwks'
    | '/backend-api/codex/thread/goal/clear'
    | '/backend-api/codex/thread/goal/get'
    | '/backend-api/codex/thread/goal/set'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  ApiAccountsRoute: typeof ApiAccountsRoute
  ApiModelsRoute: typeof ApiModelsRoute
  ApiUsageRoute: typeof ApiUsageRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  V1ModelsRoute: typeof V1ModelsRoute
  V1ResponsesRoute: typeof V1ResponsesRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
  ProvidersIndexRoute: typeof ProvidersIndexRoute
  ApiCodexInstallConfigRoute: typeof ApiCodexInstallConfigRoute
  ApiCodexModelCatalogRoute: typeof ApiCodexModelCatalogRoute
  ApiCodexUsageLimitRoute: typeof ApiCodexUsageLimitRoute
  ApiOauthCompleteRoute: typeof ApiOauthCompleteRoute
  ApiOauthManualCallbackRoute: typeof ApiOauthManualCallbackRoute
  ApiOauthStartRoute: typeof ApiOauthStartRoute
  ApiOauthStatusRoute: typeof ApiOauthStatusRoute
  ApiProvidersChatgptRoute: typeof ApiProvidersChatgptRoute
  ApiProvidersOllamaCloudRoute: typeof ApiProvidersOllamaCloudRoute
  ApiProvidersOpencodeZenRoute: typeof ApiProvidersOpencodeZenRoute
  ApiProvidersOpenrouterRoute: typeof ApiProvidersOpenrouterRoute
  ApiSystemOpenRoute: typeof ApiSystemOpenRoute
  ApiSystemVersionRoute: typeof ApiSystemVersionRoute
  BackendApiCodexModelsRoute: typeof BackendApiCodexModelsRoute
  BackendApiCodexResponsesRoute: typeof BackendApiCodexResponsesRouteWithChildren
  V1ChatCompletionsRoute: typeof V1ChatCompletionsRoute
  ApiSystemUpdateApplyRoute: typeof ApiSystemUpdateApplyRoute
  ApiSystemUpdateCheckRoute: typeof ApiSystemUpdateCheckRoute
  BackendApiCodexAgentIdentitiesJwksRoute: typeof BackendApiCodexAgentIdentitiesJwksRoute
  BackendApiCodexAnalyticsEventsEventsRoute: typeof BackendApiCodexAnalyticsEventsEventsRoute
  BackendApiCodexMemoriesTrace_summarizeRoute: typeof BackendApiCodexMemoriesTrace_summarizeRoute
  BackendApiCodexRealtimeCallsRoute: typeof BackendApiCodexRealtimeCallsRoute
  BackendApiCodexSafetyArcRoute: typeof BackendApiCodexSafetyArcRoute
  BackendApiWhamAgentIdentitiesJwksRoute: typeof BackendApiWhamAgentIdentitiesJwksRoute
  BackendApiCodexThreadGoalClearRoute: typeof BackendApiCodexThreadGoalClearRoute
  BackendApiCodexThreadGoalGetRoute: typeof BackendApiCodexThreadGoalGetRoute
  BackendApiCodexThreadGoalSetRoute: typeof BackendApiCodexThreadGoalSetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/': {
      id: '/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof ProvidersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/': {
      id: '/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/responses': {
      id: '/v1/responses'
      path: '/v1/responses'
      fullPath: '/v1/responses'
      preLoaderRoute: typeof V1ResponsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/models': {
      id: '/v1/models'
      path: '/v1/models'
      fullPath: '/v1/models'
      preLoaderRoute: typeof V1ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/usage': {
      id: '/api/usage'
      path: '/api/usage'
      fullPath: '/api/usage'
      preLoaderRoute: typeof ApiUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accounts': {
      id: '/api/accounts'
      path: '/api/accounts'
      fullPath: '/api/accounts'
      preLoaderRoute: typeof ApiAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/chat/completions': {
      id: '/v1/chat/completions'
      path: '/v1/chat/completions'
      fullPath: '/v1/chat/completions'
      preLoaderRoute: typeof V1ChatCompletionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend-api/codex/responses': {
      id: '/backend-api/codex/responses'
      path: '/backend-api/codex/responses'
      fullPath: '/backend-api/codex/responses'
      preLoaderRoute: typeof BackendApiCodexResponsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend-api/codex/models': {
      id: '/backend-api/codex/models'
      path: '/backend-api/codex/models'
      fullPath: '/backend-api/codex/models'
      preLoaderRoute: typeof BackendApiCodexModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/version': {
      id: '/api/system/version'
      path: '/api/system/version'
      fullPath: '/api/system/version'
      preLoaderRoute: typeof ApiSystemVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/open': {
      id: '/api/system/open'
      path: '/api/system/open'
      fullPath: '/api/system/open'
      preLoaderRoute: typeof ApiSystemOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/providers/openrouter': {
      id: '/api/providers/openrouter'
      path: '/api/providers/openrouter'
      fullPath: '/api/providers/openrouter'
      preLoaderRoute: typeof ApiProvidersOpenrouterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/providers/opencode-zen': {
      id: '/api/providers/opencode-zen'
      path: '/api/providers/opencode-zen'
      fullPath: '/api/providers/opencode-zen'
      preLoaderRoute: typeof ApiProvidersOpencodeZenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/providers/ollama-cloud': {
      id: '/api/providers/ollama-cloud'
      path: '/api/providers/ollama-cloud'
      fullPath: '/api/providers/ollama-cloud'
      preLoaderRoute: typeof ApiProvidersOllamaCloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/providers/chatgpt': {
      id: '/api/providers/chatgpt'
      path: '/api/providers/chatgpt'
      fullPath: '/api/providers/chatgpt'
      preLoaderRoute: typeof ApiProvidersChatgptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/status': {
      id: '/api/oauth/status'
      path: '/api/oauth/status'
      fullPath: '/api/oauth/status'
      preLoaderRoute: typeof ApiOauthStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/start': {
      id: '/api/oauth/start'
      path: '/api/oauth/start'
      fullPath: '/api/oauth/start'
      preLoaderRoute: typeof ApiOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/manual-callback': {
      id: '/api/oauth/manual-callback'
      path: '/api/oauth/manual-callback'
      fullPath: '/api/oauth/manual-callback'
      preLoaderRoute: typeof ApiOauthManualCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/complete': {
      id: '/api/oauth/complete'
      path: '/api/oauth/complete'
      fullPath: '/api/oauth/complete'
      preLoaderRoute: typeof ApiOauthCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/codex/usage-limit': {
      id: '/api/codex/usage-limit'
      path: '/api/codex/usage-limit'
      fullPath: '/api/codex/usage-limit'
      preLoaderRoute: typeof ApiCodexUsageLimitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/codex/model-catalog': {
      id: '/api/codex/model-catalog'
      path: '/api/codex/model-catalog'
      fullPath: '/api/codex/model-catalog'
      preLoaderRoute: typeof ApiCodexModelCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/codex/install-config': {
      id: '/api/codex/install-config'
      path: '/api/codex/install-config'
      fullPath: '/api/codex/install-config'
      preLoaderRoute: typeof ApiCodexInstallConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend-api/wham/agent-identities/jwks': {
      id: '/backend-api/wham/agent-identities/jwks'
      path: '/backend-api/wham/agent-identities/jwks'
      fullPath: '/backend-api/wham/agent-identities/jwks'
      preLoaderRoute: typeof BackendApiWhamAgentIdentitiesJwksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend-api/codex/safety/arc': {
      id: '/backend-api/codex/safety/arc'
      path: '/backend-api/codex/safety/arc'
      fullPath: '/backend-api/codex/safety/arc'
      preLoaderRoute: typeof BackendApiCodexSafetyArcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend-api/codex/responses/compact': {
      id: '/backend-api/codex/responses/compact'
      path: '/compact'
      fullPath: '/backend-api/codex/responses/compact'
      preLoaderRoute: typeof BackendApiCodexResponsesCompactRouteImport
      parentRoute: typeof BackendApiCodexResponsesRoute
    }
    '/backend-api/codex/realtime/calls': {
      id: '/backend-api/codex/realtime/calls'
      path: '/backend-api/codex/realtime/calls'
      fullPath: '/backend-api/codex/realtime/calls'
      preLoaderRoute: typeof BackendApiCodexRealtimeCallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend-api/codex/memories/trace_summarize': {
      id: '/backend-api/codex/memories/trace_summarize'
      path: '/backend-api/codex/memories/trace_summarize'
      fullPath: '/backend-api/codex/memories/trace_summarize'
      preLoaderRoute: typeof BackendApiCodexMemoriesTrace_summarizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend-api/codex/analytics-events/events': {
      id: '/backend-api/codex/analytics-events/events'
      path: '/backend-api/codex/analytics-events/events'
      fullPath: '/backend-api/codex/analytics-events/events'
      preLoaderRoute: typeof BackendApiCodexAnalyticsEventsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend-api/codex/agent-identities/jwks': {
      id: '/backend-api/codex/agent-identities/jwks'
      path: '/backend-api/codex/agent-identities/jwks'
      fullPath: '/backend-api/codex/agent-identities/jwks'
      preLoaderRoute: typeof BackendApiCodexAgentIdentitiesJwksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/update/check': {
      id: '/api/system/update/check'
      path: '/api/system/update/check'
      fullPath: '/api/system/update/check'
      preLoaderRoute: typeof ApiSystemUpdateCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/update/apply': {
      id: '/api/system/update/apply'
      path: '/api/system/update/apply'
      fullPath: '/api/system/update/apply'
      preLoaderRoute: typeof ApiSystemUpdateApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend-api/codex/thread/goal/set': {
      id: '/backend-api/codex/thread/goal/set'
      path: '/backend-api/codex/thread/goal/set'
      fullPath: '/backend-api/codex/thread/goal/set'
      preLoaderRoute: typeof BackendApiCodexThreadGoalSetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend-api/codex/thread/goal/get': {
      id: '/backend-api/codex/thread/goal/get'
      path: '/backend-api/codex/thread/goal/get'
      fullPath: '/backend-api/codex/thread/goal/get'
      preLoaderRoute: typeof BackendApiCodexThreadGoalGetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backend-api/codex/thread/goal/clear': {
      id: '/backend-api/codex/thread/goal/clear'
      path: '/backend-api/codex/thread/goal/clear'
      fullPath: '/backend-api/codex/thread/goal/clear'
      preLoaderRoute: typeof BackendApiCodexThreadGoalClearRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BackendApiCodexResponsesRouteChildren {
  BackendApiCodexResponsesCompactRoute: typeof BackendApiCodexResponsesCompactRoute
}

const BackendApiCodexResponsesRouteChildren: BackendApiCodexResponsesRouteChildren =
  {
    BackendApiCodexResponsesCompactRoute: BackendApiCodexResponsesCompactRoute,
  }

const BackendApiCodexResponsesRouteWithChildren =
  BackendApiCodexResponsesRoute._addFileChildren(
    BackendApiCodexResponsesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  ApiAccountsRoute: ApiAccountsRoute,
  ApiModelsRoute: ApiModelsRoute,
  ApiUsageRoute: ApiUsageRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  V1ModelsRoute: V1ModelsRoute,
  V1ResponsesRoute: V1ResponsesRoute,
  ModelsIndexRoute: ModelsIndexRoute,
  ProvidersIndexRoute: ProvidersIndexRoute,
  ApiCodexInstallConfigRoute: ApiCodexInstallConfigRoute,
  ApiCodexModelCatalogRoute: ApiCodexModelCatalogRoute,
  ApiCodexUsageLimitRoute: ApiCodexUsageLimitRoute,
  ApiOauthCompleteRoute: ApiOauthCompleteRoute,
  ApiOauthManualCallbackRoute: ApiOauthManualCallbackRoute,
  ApiOauthStartRoute: ApiOauthStartRoute,
  ApiOauthStatusRoute: ApiOauthStatusRoute,
  ApiProvidersChatgptRoute: ApiProvidersChatgptRoute,
  ApiProvidersOllamaCloudRoute: ApiProvidersOllamaCloudRoute,
  ApiProvidersOpencodeZenRoute: ApiProvidersOpencodeZenRoute,
  ApiProvidersOpenrouterRoute: ApiProvidersOpenrouterRoute,
  ApiSystemOpenRoute: ApiSystemOpenRoute,
  ApiSystemVersionRoute: ApiSystemVersionRoute,
  BackendApiCodexModelsRoute: BackendApiCodexModelsRoute,
  BackendApiCodexResponsesRoute: BackendApiCodexResponsesRouteWithChildren,
  V1ChatCompletionsRoute: V1ChatCompletionsRoute,
  ApiSystemUpdateApplyRoute: ApiSystemUpdateApplyRoute,
  ApiSystemUpdateCheckRoute: ApiSystemUpdateCheckRoute,
  BackendApiCodexAgentIdentitiesJwksRoute:
    BackendApiCodexAgentIdentitiesJwksRoute,
  BackendApiCodexAnalyticsEventsEventsRoute:
    BackendApiCodexAnalyticsEventsEventsRoute,
  BackendApiCodexMemoriesTrace_summarizeRoute:
    BackendApiCodexMemoriesTrace_summarizeRoute,
  BackendApiCodexRealtimeCallsRoute: BackendApiCodexRealtimeCallsRoute,
  BackendApiCodexSafetyArcRoute: BackendApiCodexSafetyArcRoute,
  BackendApiWhamAgentIdentitiesJwksRoute:
    BackendApiWhamAgentIdentitiesJwksRoute,
  BackendApiCodexThreadGoalClearRoute: BackendApiCodexThreadGoalClearRoute,
  BackendApiCodexThreadGoalGetRoute: BackendApiCodexThreadGoalGetRoute,
  BackendApiCodexThreadGoalSetRoute: BackendApiCodexThreadGoalSetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
